@@include('files/regular.js', {})
@@include('files/script.js', {})
@@include('files/dynamic_adapt.js', {})
@@include('files/functions.js', {})
@@include('files/forms.js', {})
@@include('files/scroll.js', {})
@@include('files/slick.min.js', {})
@@include('files/slider.js', {})